export { CertificateManager } from './resource/certificate-manager'
export { Route53Manager } from './resource/route53-manager'
export { Route53ManagerAccessRole } from './resource/route53-manager-access-role'
export { CustomCertificate, CustomCertificateProps } from './resource/custom-certificate'
export { CustomDomain, CustomDomainProps } from './resource/custom-domain'
